#!/bin/sh

#Debconf hook. We don't rely on debconf being present at this time.
if [ -e /usr/share/debconf/confmodule ];then
    . /usr/share/debconf/confmodule
    DEBCONFEXISTS="true"
    export DEBCONFEXISTS
else
    DEBCONFEXISTS="false"
    export DEBCONFEXISTS
fi

#close stdout
#exec 1<&-
##close stderr
#exec 2<&-
##open stdout as $log_file file for read and write.
#exec 1<> "/tmp/minos-core-settings.${$}.debug"
##redirect stderr to stdout
#exec 2>&1
#set -x #enable trace mode

package="minos-core-settings"
package_dir="/usr/share/minos/core-settings"
diverge_dir="${package_dir}/diverge"

users="$(busybox cat /etc/passwd | busybox awk -F: '{if ($3 >= 1000 && $3 < 60000) print $1}')"

_diverge_element() {
    _diverge__orig="${1}"
    _diverge__new="${2}"
    _diverge__backup="$(printf "%s\\n" "${_diverge__orig}" | busybox sed 's:/:##:g')"

    if ! LC_ALL=C dpkg-divert --list "${package}" | \
        grep -xFq "diversion of ${_diverge__orig} to ${diverge_dir}/${_diverge__backup} by ${package}"; then
        #busybox grep don't support the -x flag in old releases
        busybox mkdir -p "${diverge_dir}"
        dpkg-divert --package "${package}" --rename --add \
            --divert "${diverge_dir}/${_diverge__backup}" "${_diverge__orig}"

        busybox ln -s "${_diverge__new}" "${_diverge__orig}" || :
    fi
}

_undiverge_element() {
    _diverge__orig="${1}"
    _diverge__new="${2}"
    _diverge__backup="$(printf "%s\\n" "${_diverge__orig}" | busybox sed 's:/:##:g')"

    if LC_ALL=C dpkg-divert --list "${package}" | \
        grep -xFq "diversion of ${_diverge__orig} to ${diverge_dir}/${_diverge__backup} by ${package}"; then
        #busybox grep don't support the -x flag in old releases
        busybox rm -rf "${_diverge__orig}"
        dpkg-divert --package "${package}" --remove "${_diverge__orig}"
        busybox rmdir "${diverge_dir}" 2>/dev/null || :
    fi
}

_install_minos_setting() {
    for setting_file in "${@}"; do
        setting_file_target="$(busybox basename "${setting_file}")"
        setting_file_target="$(printf "%s\\n" "/${setting_file_target}" | busybox sed 's:##:/:g')"
        if [ ! -e "${setting_file_target}" ]; then
            if [ ! -d "$(busybox dirname "${setting_file_target}")" ]; then
                busybox mkdir -p "$(busybox dirname "${setting_file_target}")" >/dev/null 2>&1
            fi
            busybox ln -s "${setting_file}" "${setting_file_target}"
        fi
    done
}

_uninstall_minos_setting() {
    for setting_file in "${@}"; do
        setting_file_target="$(busybox basename "${setting_file}")"
        setting_file_target="$(printf "%s\\n" "/${setting_file_target}" | busybox sed 's:##:/:g')"
        busybox rm -rf "${setting_file_target}"
        [ -d "$(busybox dirname "${setting_file_target}")" ] && \
            busybox rmdir --ignore-fail-on-non-empty "$(busybox dirname "${setting_file_target}")"
    done
}

_get_last_file_version() {
    #get last version of a bunch of .minos-backup.* files
    [ -z "${1}" ] && return 1

    _getlastversion__files="${1}".minos-backup.*
    _getlastversion__counter="0"

    for _getlastversion__file in ${_getlastversion__files}; do
        _getlastversion__counter="$((${_getlastversion__counter} + 1))"
    done

    if [ "${_getlastversion__counter}" -eq "1" ]; then
        if [ -e "${_getlastversion__file}" ]; then
            printf "%s" "${_getlastversion__file}"
        elif [ -e "${1}" ]; then
            printf "%s" "${1}"
        fi
    else
        _getlastversion__newer="${_getlastversion__file}"
        for _getlastversion__file in ${_getlastversion__files}; do
            if [ "${_getlastversion__file}" -nt "${_getlastversion__newer}" ]; then
                _getlastversion__newer="${_getlastversion__file}"
            fi
        done
        if [ -e "${_getlastversion__newer}" ]; then
            printf "%s" "${_getlastversion__newer}"
        fi
    fi
}

_install_element_system_users() {
    test -e "${1}" || return 1
    for user in ${users}; do
        su "${user}" -c "test -f ~/.minos/not_override" && continue

        if su "${user}" -c "test -e ${2}"; then
            dist_size="$(su "${user}" -c "busybox du -sL ${1}"|busybox cut -f1)"
            user_size="$(su "${user}" -c "busybox du -sL ${2}"|busybox cut -f1)"
            if [ X"${dist_size}" = X"${user_size}" ]; then
                continue
            else
                vdotfile="minos-backup.$(busybox date +"%d-%m-%Y-%H:%M")"
                printf "%s\\n" "${package}: old $user's ${2} archive found, replacing and creating backup to ${2}.${vdotfile}"
                su "${user}" -c "busybox mv ${2} ${2}.${vdotfile}"
                su "${user}" -c "busybox cp -rL ${1} ${2}"
            fi
        else
            su "${user}" -c "busybox mkdir -p $(busybox dirname "${2}")"
            su "${user}" -c "busybox cp -rL ${1} ${2}"
        fi
    done
}

_uninstall_element_system_users() {
    test -n "${2}" || return 1
    for user in ${users}; do
        su "${user}" -c "test -f ~/.minos/not_override" && continue

        h="$(su "${user}" -c "echo ~" 2>/dev/null)" || continue
        archive="$(printf "%s\\n" "${2}" | busybox sed "s:\$HOME:${h}:g;s:~/:${h}/:;s:\"::g;s:\'::g;")"
        last_file="$(_get_last_file_version "${archive}")"

        if test -e "${1}" && su "${user}" -c "test -e ${2}"; then
            dist_size="$(su "${user}" -c "busybox du -sL ${1}"|busybox cut -f1)"
            user_size="$(su "${user}" -c "busybox du -sL ${2}"|busybox cut -f1)"
            if [ X"${dist_size}" = X"${user_size}" ]; then
                rm -rf "${archive}"
                busybox rmdir --ignore-fail-on-non-empty "$(busybox dirname "${archive}")"
            fi
        fi

        if su "${user}" -c "test -e ${last_file}"; then
            if su "${user}" -c "test -e ${2}"; then
                user_size="$(su "${user}" -c "busybox du -sL ${2}"|busybox cut -f1)"
                last_size="$(su "${user}" -c "busybox du -sL ${last_file}"|busybox cut -f1)"
                if [ X"${last_size}" = X"${user_size}" ]; then
                    continue
                else
                    printf "%s\\n" "${package}: old $user's archive found, recovering last version to ${2}"
                    su "${user}" -c "busybox mv ${last_file} ${2}"
                fi
            fi
        fi
    done
}

_ensure_setting_is_set() {
    #ensure setting($1) is enabled in configuration file($2)
    # /etc/sysctl.conf
    # /etc/fstab
    # ~/.gnupg/gpg.conf
    [ -z "${1}" ]   && return 1
    [ -z "${2}" ]   && return 1
    [ ! -f "${2}" ] && return 1

    _ensuresetting__regex="$(printf   "%s\\n" "${1}" | busybox sed 's: :[ \\t]\\+:g')"
    _ensuresetting__setting="$(printf "%s\\n" "${1}" | busybox cut -d' ' -f1)"

    if busybox grep "$(printf "^%s" "${_ensuresetting__setting}")" "${2}" >/dev/null; then
        if ! busybox grep "$(printf "^%s" "${_ensuresetting__regex}")" "${2}" >/dev/null; then
            busybox sed -i -e "/^${_ensuresetting__setting}/ s:.*:${1}:" "${2}"
        fi
    else
        if busybox grep "$(printf "^#%s[ \t]" "${_ensuresetting__setting}")" "${2}" >/dev/null; then
            busybox sed -i -e "/^#${_ensuresetting__setting}/ s:#.*:${1}:" "${2}"
        else
            busybox sed -i -e "\$ a${1}" "${2}"
        fi
    fi
}

_merge_settings() {
    [ -f "${1}" ] && [ -f "${2}" ] || return 1
    setting_file_origin="${1}"
    setting_file_target="${2}"

    OLDIFS="${IFS}"; IFS='
'
    for line in $(busybox cat "${setting_file_origin}"); do
        if ! busybox grep "^${line}$" "${setting_file_target}" > /dev/null 2>&1; then
            printf "%s\\n" "${line}" >> "${setting_file_target}"
        fi
    done; IFS="${OLDIFS}"
}

_dpkg_suspend_process() {
    #unlock standard files
    busybox mv     /var/lib/dpkg/lock           /var/lib/dpkg/lock.suspended
    busybox rm -rf /var/lib/dpkg/updates.suspended/
    busybox mv     /var/lib/dpkg/updates/       /var/lib/dpkg/updates.suspended
    busybox mkdir  /var/lib/dpkg/updates/
    busybox mv     /var/cache/apt/archives/lock /var/cache/apt/archives/lock.suspended

    #debconf missing file descriptors workaround
    busybox cp /usr/share/debconf/confmodule       /usr/share/debconf/confmodule.bk
    busybox cp "${package_dir}/usr##share##debconf##confmodule" /usr/share/debconf/confmodule

    #while apt is being executed it modifies the status file which brings conflicts
    #to new packages if they're installed/removed in abused apt instances, therefore
    #the status-old file (which represent the original state in which the first
    #apt instance was launched) is used to create temporal diffs which will be merged
    #at the end
    busybox cp     /var/lib/dpkg/status         /var/lib/dpkg/status.suspended
    busybox cp     /var/lib/dpkg/status-old     /var/lib/dpkg/status-orig
    busybox cp     /var/lib/dpkg/status-orig    /var/lib/dpkg/status
}

_dpkg_continue_process() {
    #relock standard files
    busybox rm -rf /var/lib/dpkg/updates
    busybox mv     /var/lib/dpkg/lock.suspended           /var/lib/dpkg/lock
    busybox mv     /var/lib/dpkg/updates.suspended        /var/lib/dpkg/updates
    busybox mv     /var/cache/apt/archives/lock.suspended /var/cache/apt/archives/lock
    busybox mv     /var/lib/dpkg/status.suspended         /var/lib/dpkg/status

    #debconf missing file descriptors workaround
    busybox mv     /usr/share/debconf/confmodule.bk       /usr/share/debconf/confmodule

    #keep status-old file to survive multiple abused apt instances
    busybox mv     /var/lib/dpkg/status-orig              /var/lib/dpkg/status-old
}

_dpkg_sync_status_db() {
    _dpkg_sync_status_db_script="/var/lib/dpkg/dpkg-sync-status-db"
    _dpkg_sync_status_db_script_generator() {
        printf "%s\\n" "#!/bin/sh"
        printf "%s\\n" "#autogenerated by ${package}: $(date +%d-%m-%Y:%H:%M)"
        printf "\\n"
        printf "%s\\n" '##close stdout'
        printf "%s\\n" '#exec 1<&-'
        printf "%s\\n" '##close stderr'
        printf "%s\\n" '#exec 2<&-'
        printf "%s\\n" '##open stdout as $log_file file for read and write.'
        printf "%s\\n" "#exec 1<> /tmp/${package}.\${$}.debug"
        printf "%s\\n" '##redirect stderr to stdout'
        printf "%s\\n" '#exec 2>&1'
        printf "%s\\n" '#set -x #enable trace mode'
        printf "\\n"
        printf "%s\\n" "while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done"
        printf "\\n"
        printf "%s\\n" 'pkgs__add="$(cat /var/lib/apt/apt-add-queue)"'
        printf "%s\\n" 'if [ -n "${pkgs__add}" ]; then'
        printf "%s\\n" '  for pkg in $pkgs__add; do'
        printf "%s\\n" '    if ! busybox grep "^Package: ${pkg}$" /var/lib/dpkg/status >/dev/null 2>&1; then'
        printf "%s\\n" '      if [ -f /var/lib/dpkg/status-append-queue ]; then'
        printf "%s\\n" '        busybox sed -n "/Package: ${pkg}$/,/^$/p" \'
        printf "%s\\n" "          /var/lib/dpkg/status-append-queue >> /var/lib/dpkg/status"
        printf "%s\\n" '      fi'
        printf "%s\\n" "    fi"
        printf "%s\\n" "  done"
        printf "%s\\n" "fi"
        printf "\\n"
        printf "%s\\n" 'pkgs__rm="$(cat /var/lib/apt/apt-rm-queue 2>/dev/null)"'
        printf "%s\\n" 'if [ -n "${pkgs__rm}" ]; then'
        printf "%s\\n" '  for pkg in $pkgs__rm; do'
        printf "%s\\n" '    busybox sed -i "/Package: ${pkg}$/,/^$/d" /var/lib/dpkg/status'
        printf "%s\\n" "  done"
        printf "%s\\n" "fi"
        printf "\\n"
        printf "%s\\n" "mv /var/lib/apt/apt-add-queue /var/lib/apt/apt-add-queue.bk 2>/dev/null"
        printf "%s\\n" "mv /var/lib/apt/apt-rm-queue  /var/lib/apt/apt-rm-queue.bk  2>/dev/null"
        printf "%s\\n" "mv /var/lib/dpkg/status-append-queue /var/lib/dpkg/status-append-queue.bk 2>/dev/null"
        printf "\\n"
        printf "%s\\n" "rm -rf /var/lib/apt/apt-add-queue /var/lib/apt/apt-rm-queue"
        printf "%s\\n" "rm -rf ${_dpkg_sync_status_db_script}"
    }

    _dpkg_sync_status_db_script_generator > "${_dpkg_sync_status_db_script}"
    chmod +x "${_dpkg_sync_status_db_script}"
    _daemonize /bin/sh -c "${_dpkg_sync_status_db_script}"
}

_daemonize() {
    #http://blog.n01se.net/blog-n01se-net-p-145.html
    [ -z "${1}" ] && return 1
    (   #1. fork, to guarantee the child is not a process
        #group leader, necessary for setsid) and have the
        #parent exit (to allow control to return to the shell)

        #2. redirect stdin/stdout/stderr before running child
        [ -t 0 ] && exec  </dev/null
        [ -t 1 ] && exec  >/dev/null
        [ -t 2 ] && exec 2>/dev/null
        if ! command -v "setsid" >/dev/null 2>&1; then
            #2.1 guard against HUP and INT (in child)
            trap '' 1 2
        fi

        #3. ensure cwd isn't a mounted fs so it does't block
        #umount invocations
        cd /

        #4. umask (leave this to caller)
        #umask 0

        #5. close unneeded fds
        #XCU 2.7 Redirection says: open files are represented by
        #decimal numbers starting with zero. The largest possible
        #value is implementation-defined; however, all
        #implementations shall support at least 0 to 9, inclusive,
        #for use by the application.
        i=3; while [ "${i}" -le "9" ]; do
            eval "exec ${i}>&-"
            i="$(($i + 1))"
        done

        #6. create new session, so the child has no
        #controlling terminal, this prevents the child from
        #accesing a terminal (using /dev/tty) and getting
        #signals from the controlling terminal (e.g. HUP, INT)
        if command -v "setsid" >/dev/null 2>&1; then
            exec setsid "$@"
        elif command -v "nohup" >/dev/null 2>&1; then
            exec nohup "$@" >/dev/null 2>&1
        else
            if [ ! -f "${1}" ]; then
                "$@"
            else
                exec "$@"
            fi
        fi
    ) &
    #2.2 guard against HUP (in parent)
    if ! command -v "setsid" >/dev/null 2>&1 \ &&
       ! command -v "nohup"  >/dev/null 2>&1; then
        disown -h "${!}"
    fi
}

_apt_add_queue() {
    for pkg in "${@}"; do
        if  busybox grep "${pkg}" /var/lib/apt/apt-rm-queue >/dev/null 2>&1; then
            busybox sed -i "/^${pkg}$/d" /var/lib/apt/apt-rm-queue
        else
            if ! busybox grep "^Package: ${pkg}$" /var/lib/dpkg/status >/dev/null 2>&1; then
                printf "%s\\n" "${pkg}" >> /var/lib/apt/apt-add-queue
            fi
        fi
    done; unset pkg
}

_apt_rm_queue() {
    for pkg in "${@}"; do
        if  busybox grep "${pkg}" /var/lib/apt/apt-add-queue >/dev/null 2>&1; then
            busybox sed -i "/^${pkg}$/d" /var/lib/apt/apt-add-queue
        else
            if busybox grep "^Package: ${pkg}$" /var/lib/dpkg/status >/dev/null 2>&1; then
                printf "%s\\n" "${pkg}" >> /var/lib/apt/apt-rm-queue
            fi
        fi
    done; unset pkg
}

_apt_install() {
    [ -z "${1}" ] && return
    _apt_add_queue $(printf "%s\\n" "${@}" | busybox sed "s:${package}::g")
}

_apt_purge() {
    [ -z "${1}" ] && return
    _apt_rm_queue $(printf "%s\\n" "${@}" | busybox sed "s:${package}::g")
}

_apt_run() {
    [ ! -f /var/lib/apt/apt-add-queue ] && [ ! -f /var/lib/apt/apt-rm-queue ] && return

    pkgs__add="$(cat /var/lib/apt/apt-add-queue 2>/dev/null)"
    if [ -n "${pkgs__add}" ]; then
        _dpkg_suspend_process
        busybox awk '/^Package: /{print $2}' /var/lib/dpkg/status | \
            busybox sort > /var/lib/dpkg/status-pkgs.orig
        _apt_run__output="$(DEBIAN_FRONTEND=noninteractive apt-get install  \
            --no-install-recommends -y -o Dpkg::Options::="--force-confdef" \
            -o Dpkg::Options::="--force-confold" --force-yes ${pkgs__add} 2>&1)" || \
            printf "%s\\n" "${_apt_run__output}" >&2
        busybox awk '/^Package: /{print $2}' /var/lib/dpkg/status | \
            busybox sort > /var/lib/dpkg/status-pkgs.current
        _dpkg__added_pkgs="$(busybox diff -Naur /var/lib/dpkg/status-pkgs.orig \
            /var/lib/dpkg/status-pkgs.current | busybox awk '/^\+[a-zA-Z]/{gsub("^+","");print;}')"
        busybox rm -rf /var/lib/dpkg/status-pkgs*
        #add dependencies
        if [ -n "${_dpkg__added_pkgs}" ]; then
            printf "%s\\n" "${_dpkg__added_pkgs}" >> /var/lib/apt/apt-add-queue
            printf "%s\\n" "$(busybox sort /var/lib/apt/apt-add-queue | busybox uniq)" \
                > /var/lib/apt/apt-add-queue
        fi

        #extract dpkg status output to append it at the end
        for pkg in $_dpkg__added_pkgs; do
            busybox sed -n '/Package: '"${pkg}"'$/,/^$/p' /var/lib/dpkg/status \
                >> /var/lib/dpkg/status-append-queue
        done
        _dpkg_continue_process
    fi

    pkgs__rm="$(cat /var/lib/apt/apt-rm-queue 2>/dev/null)"
    if [ -n "${pkgs__rm}" ]; then
        _dpkg_suspend_process
        busybox awk '/^Package: /{print $2}' /var/lib/dpkg/status | \
            busybox sort > /var/lib/dpkg/status-pkgs.orig
        _apt_run__output="$(DEBIAN_FRONTEND=noninteractive apt-get purge \
            -y ${pkgs__rm} 2>&1)" || printf "%s\\n" "${_apt_run__output}" >&2
        busybox awk '/^Package: /{print $2}' /var/lib/dpkg/status | \
            busybox sort > /var/lib/dpkg/status-pkgs.current
        _dpkg__removed_pkgs="$(busybox diff -Naur /var/lib/dpkg/status-pkgs.orig \
            /var/lib/dpkg/status-pkgs.current | busybox awk '/^-[a-zA-Z]/{gsub("^-","");print;}')"
        busybox rm -rf /var/lib/dpkg/status-pkgs*
        #remove dependencies
        if [ -n "${_dpkg__removed_pkgs}" ]; then
            printf "%s\\n" "${_dpkg__removed_pkgs}" >> /var/lib/apt/apt-rm-queue
            printf "%s\\n" "$(busybox sort /var/lib/apt/apt-rm-queue | busybox uniq)" \
                > /var/lib/apt/apt-rm-queue
        fi
        _dpkg_continue_process
    fi

    _dpkg_sync_status_db
}

_enable_setting() {
    case "${1}" in
        kernel)
            _install_minos_setting "${package_dir}/etc##sysctl.d##99-swappiness.conf"
            _install_minos_setting "${package_dir}/etc##sysctl.d##99-printk.conf"
            ;;

        disable-ipv6)
            _install_minos_setting "${package_dir}/etc##sysctl.d##99-disable-ipv6.conf"
            ;;

        apt)
            apt-config dump | grep '^APT::Install-Recommends "false";$' >/dev/null 2>&1 ||     \
                _install_minos_setting "${package_dir}/etc##apt##apt.conf.d##05disable-recommends"

            apt-config dump | grep '^APT::Install-Suggests "false";$'   >/dev/null 2>&1 ||   \
                _install_minos_setting "${package_dir}/etc##apt##apt.conf.d##05disable-suggests"
            ;;

        sudo)
            busybox sed -i "/^#includedir.*\/etc\/sudoers\.d$/d" /etc/sudoers
            busybox sed -i -e "\$ a#includedir /etc/sudoers.d"   /etc/sudoers
            _install_minos_setting "${package_dir}/etc##sudoers.d##minos-core"
            ;;

        ssh) _diverge_element /etc/ssh/ssh_config "${package_dir}/etc##ssh##ssh_config" ;;
        git) _diverge_element /etc/gitconfig "${package_dir}/etc##gitconfig" ;;

        motd)
            _diverge_element /etc/issue     "${package_dir}/etc##issue"
            _diverge_element /etc/issue.net "${package_dir}/etc##issue.net"
            _diverge_element /etc/legal     "${package_dir}/etc##legal"
            _diverge_element /etc/update-motd.d/00-header    "${package_dir}/etc##update-motd.d##00-header"
            _diverge_element /etc/update-motd.d/10-help-text "${package_dir}/etc##update-motd.d##10-help-text"

            if [ ! -f /etc/update-motd.d/10-minos-sysinfo ]; then
                _install_minos_setting "${package_dir}/etc##update-motd.d##10-minos-sysinfo"
            fi

            #disable landscape + cloud ads
            chmod -x /etc/update-motd.d/51-cloudguest        && mv /etc/update-motd.d/51-cloudguest        /etc/update-motd.d/51-cloudguest.disabled        || :
            chmod -x /etc/update-motd.d/50-landscape-sysinfo && mv /etc/update-motd.d/50-landscape-sysinfo /etc/update-motd.d/50-landscape-sysinfo.disabled || :
            chmod -x /etc/update-motd.d/98-cloudguest        && mv /etc/update-motd.d/98-cloudguest        /etc/update-motd.d/98-cloudguest.disabled        || :
            ;;

        tmpfs) _ensure_setting_is_set "tmpfs /tmp tmpfs defaults,noatime,noexec,nosuid,nodev,size=10% 0 0" /etc/fstab ;;

        locales)
            locale-gen en_US en_US.UTF-8 && locale-gen
            #https://bugs.launchpad.net/ubuntu/+source/pam/+bug/155794
            if [ ! -f /etc/default/locale ]; then
                printf "%s\\n%s\\n" 'LANG="en_US.UTF-8"' 'LANGUAGE="en_US:en"' > /etc/default/locale
            else
                if ! busybox grep "LANG=" /etc/default/locale | busybox grep "UTF-8" >/dev/null; then
                    busybox sed -i -e "/LANG=/ s:\"$:.UTF-8\":" /etc/default/locale
                fi
            fi
            ;;

        minos-bash)
            _install_minos_setting "${package_dir}/etc##profile.d##minos-bash.sh"
            ;;

        bash-profile)
            _install_minos_setting "${package_dir}/etc##skel##.bash_profile"
            _install_element_system_users '/etc/skel/.bash_profile' '~/.bash_profile'
            ;;

        #app-core)
            #for user in ${users}; do
                #su "${user}" -c "busybox id | busybox grep '(sudo)\|(admin)\|(wheel)'" >/dev/null 2>&1 || continue
                #h="$(su "${user}" -c "echo ~" 2>/dev/null)" || continue

                #userpkgs="$(busybox awk -v pattern="^app-core"       \
                    #'$0 ~ pattern {$1=""; print substr($0,2); exit}' \
                    #"${h}"/.minos/config 2>/dev/null)"

                #[ -z "${userpkgs}" ] && continue

                #printf "%s\\n" "${package}: adding to the apt queue, ${user}'s defined pkgs: ${userpkgs} ..."
                #_apt_install ${userpkgs}
            #done

            #globalpkgs="$(busybox awk -v pattern="^app-core"         \
                    #'$0 ~ pattern {$1=""; print substr($0,2); exit}' \
                     #/etc/minos/config 2>/dev/null)"

            #if [ -n "${globalpkgs}" ]; then
                #printf "%s\\n" "${package}: adding to the apt queue, system defined pkgs: ${globalpkgs} ..."
                #_apt_install ${globalpkgs}
            #fi
            #;;

        #app-purge)
            #for user in ${users}; do
                #su "${user}" -c "busybox id | busybox grep '(sudo)\|(admin)\|(wheel)'" >/dev/null 2>&1 || continue
                #h="$(su "${user}" -c "echo ~" 2>/dev/null)" || continue

                #rm_userpkgs="$(busybox awk -v pattern="^app-purge"   \
                    #'$0 ~ pattern {$1=""; print substr($0,2); exit}' \
                    #"${h}/.minos/config" 2>/dev/null)"

                #[ -z "${rm_userpkgs}" ] && continue

                #printf "%s\\n" "${package}: removing from the apt queue, ${user}'s defined pkgs: ${rm_userpkgs} ..."
                #_apt_purge ${rm_userpkgs}
            #done

            #rm_globalpkgs="$(busybox awk -v pattern="^app-purge"     \
                    #'$0 ~ pattern {$1=""; print substr($0,2); exit}' \
                     #/etc/minos/config 2>/dev/null)"

            #if [ -n "${rm_globalpkgs}" ]; then
                #printf "%s\\n" "${package}: removing from the apt queue, system defined pkgs: ${rm_globalpkgs} ..."
                #_apt_purge ${rm_globalpkgs}
            #fi
            #;;

         dotfiles)
            for user in ${users}; do
                su "${user}" -c "test -f ~/.minos/not_override" && continue
                h="$(su "${user}" -c "echo ~" 2>/dev/null)"     || continue

                dotrepo="$(busybox awk -v pattern="^dotfiles"        \
                    '$0 ~ pattern {$1=""; print substr($0,2); exit}' \
                    "${h}/.minos/config" 2>/dev/null)"

                if [ -z "${dotrepo}" ]; then
                    dotrepo="$(busybox awk -v pattern="^dotfiles"    \
                    '$0 ~ pattern {$1=""; print substr($0,2); exit}' \
                    /etc/minos/config 2>/dev/null)"
                fi

                [ -z "${dotrepo}" ] && continue

                bdotrepo="$(busybox basename "${dotrepo}")"
                busybox mkdir -p /tmp/minos-core-setting
                git clone --depth=1 "${dotrepo}" /tmp/minos-core-setting/"${bdotrepo}" >/dev/null

                for dotfile in /tmp/minos-core-setting/"${bdotrepo}"/.*; do
                    [ ! -e "${dotfile}" ] && continue
                    bdotfile="$(busybox basename "${dotfile}")"

                    if [ X"${bdotfile}" = X"." ] || [ X"${bdotfile}" = X".." ]; then
                        continue
                    fi

                    if [ -e "${h}"/"${bdotfile}" ]; then
                        busybox diff -qr "${dotfile}" "${h}"/"${bdotfile}" >/dev/null 2>&1 && continue
                    fi

                    ownerdotfile="$(stat -c %U "${h}")" || ownerdotfile="${user}"
                    groupdotfile="$(stat -c %G "${h}")" || groupdotfile="${user}"

                    if [ -e "${h}"/"${bdotfile}" ]; then
                        vdotfile="minos-backup.$(busybox date +"%d-%m-%Y-%H:%M")"
                        printf "%s\\n" "${package}: old $user's ~/.${bdotfile} archive found, replacing and creating backup in ~/.${bdotfile}.${vdotfile}"
                        su "${user}" -c "busybox mv \"${h}\"/\"${bdotfile}\" \"${h}\"/\"${bdotfile}\".\"${vdotfile}\"" >/dev/null 2>&1
                    fi

                    busybox cp    -r "${dotfile}" "${h}"/"${bdotfile}"
                    busybox chown -R "${ownerdotfile}":"${groupdotfile}" "${h}"/"${bdotfile}"

                    #special case, don't remove ssh keys
                    old_ssh_conf="$(_get_last_file_version "${h}"/.ssh)"
                    if [ -n "${old_ssh_conf}" ] && [ ! X"${old_ssh_conf}" = X"${h}"/.ssh ]; then
                        busybox cp -- "${old_ssh_conf}"/* "${h}"/.ssh/
                    fi
                done; busybox rm -rf /tmp/minos-core-setting/
            done
            ;;

       aliases)
            _install_minos_setting "${package_dir}/etc##skel##.aliases"
            _install_element_system_users '/etc/skel/.aliases' '~/.aliases'
            ;;

        vim)
            _install_minos_setting "${package_dir}/etc##skel##.vimrc"
            _install_element_system_users '/etc/skel/.vimrc' '~/.vimrc'

            if [ -d "${package_dir}/cache/vim/bundle/vundle/.git/" ]; then
                (cd "${package_dir}/cache/vim/bundle/vundle" && git pull)  >/dev/null 2>&1
            else
                busybox rm -rf "${package_dir}/cache/vim"
                git clone --depth=1 https://github.com/javier-lopez/vundle.git \
                    "${package_dir}/cache/vim/bundle/vundle/" >/dev/null
            fi

            if [ -d "${package_dir}/cache/vim/bundle/vundle/.git/" ]; then
                busybox rm -rf   /etc/skel/.vim
                busybox mkdir -p /etc/skel/.vim/bundle
                busybox cp -rL   "${package_dir}/cache/vim/bundle/vundle/" /etc/skel/.vim/bundle/

                for user in ${users}; do
                    su "${user}" -c "test -f ~/.minos/not_override" && continue
                    su "${user}" -c "busybox mkdir -p ~/.vim/bundle/"
                    su "${user}" -c "test -d ~/.vim/bundle/vundle/" || \
                        su "${user}" -c "busybox cp -rL /etc/skel/.vim/bundle/vundle ~/.vim/bundle/vundle"
                    printf "%s\\n" "${package}: installing ${user}'s vim plugins"
                    su "${user}" -c "vim -es -u ~/.vimrc -c \"BundleInstall\" -c qa" >/dev/null 2>&1
                    #su "${user}" -c "vim +BundleInstall +qall" >/dev/null 2>&1
                done
            fi
            ;;

        tmux)
            _install_minos_setting "${package_dir}/etc##skel##.tmux.conf"
            _install_element_system_users '/etc/skel/.tmux.conf' '~/.tmux.conf'

            if [ -d "${package_dir}/cache/tmux/plugins/tundle/.git/" ]; then
                (cd "${package_dir}/cache/tmux/plugins/tundle" && git pull) >/dev/null 2>&1
            else
                busybox rm -rf "${package_dir}/cache/tmux"
                git clone --depth=1 https://github.com/javier-lopez/tundle \
                    "${package_dir}/cache/tmux/plugins/tundle" >/dev/null
            fi

            if [ -d "${package_dir}/cache/tmux/plugins/tundle/.git/" ]; then
                busybox rm -rf   /etc/skel/.tmux
                busybox mkdir -p /etc/skel/.tmux/plugins
                busybox cp -rL   "${package_dir}/cache/tmux/plugins/tundle" /etc/skel/.tmux/plugins/
                for user in ${users}; do
                    su "${user}" -c "test -f ~/.minos/not_override" && continue
                    su "${user}" -c "busybox mkdir -p ~/.tmux/plugins/" > /dev/null 2>&1
                    su "${user}" -c "test -d ~/.tmux/plugins/tundle/" || \
                        su "${user}" -c "busybox cp -rL /etc/skel/.tmux/plugins/tundle ~/.tmux/plugins/tundle"
                    printf "%s\\n" "${package}: installing ${user}'s tmux plugins"
                    su "${user}" -c "sh ~/.tmux/plugins/tundle/scripts/install_plugins.sh" >/dev/null 2>&1
                done
            fi
            ;;

        shundle)
            _install_minos_setting "${package_dir}/etc##skel##.profile.d##shundle.sh"
            for user in ${users}; do
                su "${user}" -c "test -f ~/.minos/not_override" && continue
                su "${user}" -c "busybox mkdir ~/.profile.d" >/dev/null 2>&1
            done
            _install_element_system_users '/etc/skel/.profile.d/shundle.sh' '~/.profile.d/shundle.sh'

            if [ -d "${package_dir}/cache/shundle/bundle/shundle/.git/" ]; then
                (cd "${package_dir}/cache/shundle/bundle/shundle" && git pull) > /dev/null 2>&1
            else
                busybox rm -rf "${package_dir}/cache/shundle"
                git clone --depth=1 https://github.com/javier-lopez/shundle \
                    "${package_dir}/cache/shundle/bundle/shundle" >/dev/null
            fi

            if [ -d "${package_dir}/cache/shundle/bundle/shundle/.git/" ]; then
                busybox rm -rf /etc/skel/.shundle
                busybox cp -rL "${package_dir}/cache/shundle/" /etc/skel/.shundle

                for user in ${users}; do
                    su "${user}" -c "test -f ~/.minos/not_override" && continue
                    su "${user}" -c "busybox mkdir -p ~/.shundle/bundle/" > /dev/null 2>&1
                    su "${user}" -c "test -d ~/.shundle/bundle/shundle/" || \
                        su "${user}" -c "busybox cp -rL /etc/skel/.shundle/bundle/shundle ~/.shundle/bundle/shundle"
                    printf "%s\\n" "${package}: installing ${user}'s shundle plugins"
                    su "${user}" -c "SHUNDLE_HOME=~/.shundle SHUNDLE_RC=~/.bashrc \
                        ~/.shundle/bundle/shundle/bin/shundle install" >/dev/null 2>&1
                    su "${user}" -c "SHUNDLE_HOME=~/.shundle SHUNDLE_RC=~/.profile.d/shundle.sh \
                        ~/.shundle/bundle/shundle/bin/shundle install" >/dev/null 2>&1
                done
            fi
            ;;

        hooks)
            globalhook="$(busybox awk -v pattern="^hook"             \
                    '$0 ~ pattern {$1=""; print substr($0,2); exit}' \
                     /etc/minos/config 2>/dev/null)"

            if [ -n "${globalhook}" ]; then
                (busybox wget "${globalhook}" -O "/bin/${package}-hook" || \
                    wget "${globalhook}" -O "/bin/${package}-hook") >/dev/null
                if [ -f "/bin/${package}-hook" ]; then
                    busybox chmod +x "/bin/${package}-hook"
                    printf "%s\\n" "${package}: executing system defined hook: ${globalhook}"
                    "/bin/${package}-hook" core
                fi
            fi

            for user in ${users}; do
                su "${user}" -c "test -f ~/.minos/not_override" && continue
                h="$(su "${user}" -c "echo ~" 2>/dev/null)"     || continue

                userhook="$(busybox awk -v pattern="^hook"           \
                    '$0 ~ pattern {$1=""; print substr($0,2); exit}' \
                    "${h}"/.minos/config 2>/dev/null)"

                [ -z "${userhook}" ] && continue

                (su "${user}" -c "busybox wget ${userhook} -O ~/.${package}-hook" || \
                    su "${user}" -c "wget ${userhook} -O ~/.${package}-hook") >/dev/null

                su "${user}" -c "test -f  ~/.${package}-hook" || continue
                su "${user}" -c "busybox chmod +x ~/.${package}-hook"

                printf "%s\\n" "${package}: executing $user's defined hook: ${userhook}"
                su "${user}" -c "~/.${package}-hook core"
            done
            ;;
    esac
}

_disable_setting() {
    case "${1}" in
        kernel)
            _uninstall_minos_setting "${package_dir}/etc##sysctl.d##99-swappiness.conf"
            _uninstall_minos_setting "${package_dir}/etc##sysctl.d##99-printk.conf"
            ;;

        disable-ipv6)
            _uninstall_minos_setting "${package_dir}/etc##sysctl.d##99-disable-ipv6.conf"
            ;;

        apt)
            rm -rf /etc/apt/apt.conf.d/05disable-recommends
            rm -rf /etc/apt/apt.conf.d/05disable-suggests
            ;;

        sudo) _uninstall_minos_setting "${package_dir}/etc##sudoers.d##minos-core" ;;
        ssh) _undiverge_element /etc/ssh/ssh_config "${package_dir}/etc##ssh##ssh_config" ;;
        git) _undiverge_element /etc/gitconfig "${package_dir}/etc##gitconfig" ;;

        motd)
            _undiverge_element /etc/issue     "${package_dir}/etc##issue"
            _undiverge_element /etc/issue.net "${package_dir}/etc##issue.net"
            _undiverge_element /etc/legal     "${package_dir}/etc##legal"
            _undiverge_element /etc/update-motd.d/00-header    "${package_dir}/etc##update-motd.d##00-header"
            _undiverge_element /etc/update-motd.d/10-help-text "${package_dir}/etc##update-motd.d##10-help-text"

            _uninstall_minos_setting "${package_dir}/etc##update-motd.d##10-minos-sysinfo"

            #re-enable landscape + cloud ads
            chmod +x /etc/update-motd.d/51-cloudguest.disabled        && mv /etc/update-motd.d/51-cloudguest.disabled        /etc/update-motd.d/51-cloudguest        || :
            chmod +x /etc/update-motd.d/50-landscape-sysinfo.disabled && mv /etc/update-motd.d/50-landscape-sysinfo.disabled /etc/update-motd.d/50-landscape-sysinfo || :
            chmod +x /etc/update-motd.d/98-cloudguest.disabled        && mv /etc/update-motd.d/98-cloudguest.disabled        /etc/update-motd.d/98-cloudguest        || :
            ;;

        tmpfs)
            busybox sed -i "/^tmpfs \/tmp tmpfs defaults,noatime,noexec,nosuid,nodev,size=10% 0 0/d" /etc/fstab
            ;;

        locales) : ;;
        minos-bash) _uninstall_minos_setting "${package_dir}/etc##profile.d##minos-bash.sh" ;;

        bash-profile)
            _uninstall_element_system_users /etc/skel/.bash_profile '~/.bash_profile'
            _uninstall_minos_setting "${package_dir}/etc##skel##.bash_profile"
            ;;

        #app-core|app-purge) : ;; #what would be the reverse process?

        dotfiles)
            for user in ${users}; do
                su "${user}" -c "test -f ~/.minos/not_override" && continue
                h="$(su "${user}" -c "echo ~" 2>/dev/null)"     || continue

                dotrepo="$(busybox awk -v pattern="^dotfiles"        \
                    '$0 ~ pattern {$1=""; print substr($0,2); exit}' \
                    "${h}"/.minos/config 2>/dev/null)"

                if [ -z "${dotrepo}" ]; then
                    dotrepo="$(busybox awk -v pattern="^dotfiles"    \
                    '$0 ~ pattern {$1=""; print substr($0,2); exit}' \
                    /etc/minos/config 2>/dev/null)"
                fi

                [ -z "${dotrepo}" ] && continue

                bdotrepo="$(busybox basename "${dotrepo}")"
                busybox mkdir -p /tmp/"${package}"
                git clone --depth=1  "${dotrepo}" /tmp/"${package}/${bdotrepo}" >/dev/null

                for dotfile in /tmp/"${package}/${bdotrepo}"/.*; do
                    [ ! -e "${dotfile}" ] && continue
                    bdotfile="$(busybox basename "${dotfile}")"

                    #special case, don't recover ssh keys
                    if [ X"${bdotfile}" = X"." ] || [ X"${bdotfile}" = X".." ] || [ X"${bdotfile}" = X".ssh" ]; then
                        continue
                    fi

                    if [ -e "${h}"/"${bdotfile}" ]; then
                        printf "%s\\n" "${package}: old $user's ~/.${bdotfile} archive found, recovering last state"
                        _uninstall_element_system_users "${dotfile}" "${bdotfile}"
                    fi

                done; busybox rm -rf /tmp/"${package}"/
            done
            ;;

       aliases)
            _uninstall_element_system_users '/etc/skel/.aliases' '~/.aliases'
            _uninstall_minos_setting "${package_dir}/etc##skel##.aliases"
            ;;

        vim)
            _uninstall_element_system_users '/etc/skel/.vimrc' '~/.vimrc'
            _uninstall_minos_setting "${package_dir}/etc##skel##.vimrc"
            busybox rm -rf /etc/skel/.vim/bundle/vundle
            busybox rmdir  /etc/skel/.vim/bundle/ 2>/dev/null
            busybox rmdir  /etc/skel/.vim/        2>/dev/null
            ;;

        tmux)
            _uninstall_element_system_users '/etc/skel/.tmux.conf' '~/.tmux.conf'
            _uninstall_minos_setting "${package_dir}/etc##skel##.tmux.conf"
            busybox rm -rf /etc/skel/.tmux/plugins/tundle
            busybox rmdir  /etc/skel/.tmux/plugins/ 2>/dev/null
            busybox rmdir  /etc/skel/.tmux          2>/dev/null
            ;;

        shundle)
            _uninstall_element_system_users '/etc/skel/.profile.d/shundle.sh' '~/.profile.d/shundle.sh'
            _uninstall_element_system_users '/etc/skel/.shundle' '~/.shundle'
            _uninstall_minos_setting "${package_dir}/etc##skel##.profile.d##shundle.sh"

            busybox rm -rf /etc/skel/.shundle/bundle/shundle
            busybox rmdir  /etc/skel/.shundle/bundle/ 2>/dev/null
            busybox rmdir  /etc/skel/.shundle/        2>/dev/null
            ;;

        hooks) : ;;
    esac
}

case "${1}" in
    configure)
        #bugs, bugs everywhere: https://github.com/gitpython-developers/GitPython/issues/295
        chmod -x /usr/lib/git-core/git-credential-cache--daemon || :

        if [ "${DEBCONFEXISTS}" = "true" ]; then
            #get user settings
            db_get "${package}"/settings
            settings="${RET}"

            #get default settings
            db_metaget "${package}"/settings Choices
            default_settings="${RET}"
        fi

        #enable selected items
        for setting in ${settings}; do
            setting="${setting%,*}" #remove ',' from tail
            _enable_setting "${setting}"

            default_settings="$(printf "%s\\n" "${default_settings}" | busybox sed 's:'"${setting}"'[, ]*::')"
        done

        #disable not selected items
        for not_selected_setting in ${default_settings}; do
            not_selected_setting="${not_selected_setting%,*}" #remove ',' from tail
            _disable_setting "${not_selected_setting}"
        done

        #apply apt/dpkg changes
        #_apt_run

        chmod +x /usr/lib/git-core/git-credential-cache--daemon || :
        ;;

    upgrade|remove) #abusing postinst to avoid repeating code in prerm
        if [ "${DEBCONFEXISTS}" = "true" ]; then
            #get default settings
            db_metaget "${package}"/settings Choices
            default_settings="${RET}"
        fi

        #enable selected items
        for setting in ${default_settings}; do
            setting="${setting%,*}" #remove ',' from tail
            _disable_setting "${setting}"
        done
        ;;

    abort-upgrade|abort-deconfigure|abort-remove) : ;;

    *)
        printf "%s\\n" "${0} called with unknown argument \`${1}'" 1>&2
        exit 1
        ;;
esac

#DEBHELPER#
exit 0
